install: gradle wrapper --gradle-version 4.2
language: java
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.m2
jdk:
- oraclejdk8
script: ./travis/build.sh
before_install:
- chmod +x ./travis/build.sh

