language: java
sudo: false
dist: xenial
cache:
  directories:
    - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
- oraclejdk11
install: true
script: ./travis/build.sh
before_install:
- chmod +x ./travis/build.sh

